### ISSUE TITLE
Issue with using Selective context on dataset pubmed

### ISSUE THREAD

**Issue by Sriharsha-hatwar** [liyucheng09/LLMs_Memorize#23]
> Processing sequentially..:   5%|██████▉                                                                                                                                    | 333/6658 [11:29<3:41:37,  2.10s/it]
Token indices sequence length is longer than the specified maximum sequence length for this model (2515 > 1024). Running this sequence through the model will result in indexing errors
Processing sequentially..:   5%|██████▉                                                                                                                                    | 333/6658 [11:31<3:38:55,  2.08s/it]
Traceback (most recent call last):
  File "/work/pi_dhruveshpate_umass_edu/compressed-llm/experiments/shatwar/temp/llm-context/src/extend_dataset.py", line 164, in <module>
    dataset = PubMedExtended()
  File "/work/pi_dhruveshpate_umass_edu/compressed-llm/experiments/shatwar/temp/llm-context/src/extend_dataset.py", line 108, in __init__
    self.extended_dataset = self.__execute_selective_context(model_type, compression_ratio, data_folder)
  File "/work/pi_dhruveshpate_umass_edu/compressed-llm/experiments/shatwar/temp/llm-context/src/extend_dataset.py", line 139, in __execute_selective_context
    compressed_context, _ = sc(article_text, compression_ratio)
  File "/work/pi_dhruveshpate_umass_edu/compressed-llm/experiments/shatwar/temp/llm-context/Selective_Context/selective_context.py", line 301, in __call__
    sent_lus, phrase_lus, token_lus = self._lexical_unit(sents)
  File "/work/pi_dhruveshpate_umass_edu/compressed-llm/experiments/shatwar/temp/llm-context/Selective_Context/selective_context.py", line 176, in _lexical_unit
    tokens, self_info = self.get_self_information(sent)
  File "/work/pi_dhruveshpate_umass_edu/compressed-llm/experiments/shatwar/temp/llm-context/Selective_Context/selective_context.py", line 108, in _get_self_info_via_gpt2
    outputs = self.model(**encoding)
  File "/work/pi_dhruveshpate_umass_edu/compressed-llm/envs/context-compressio-py3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/work/pi_dhruveshpate_umass_edu/compressed-llm/envs/context-compressio-py3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/work/pi_dhruveshpate_umass_edu/compressed-llm/envs/context-compressio-py3.10/lib/python3.10/site-packages/transformers/models/gpt2/modeling_gpt2.py", line 1074, in forward
    transformer_outputs = self.transformer(
  File "/work/pi_dhruveshpate_umass_edu/compressed-llm/envs/context-compressio-py3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/work/pi_dhruveshpate_umass_edu/compressed-llm/envs/context-compressio-py3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/work/pi_dhruveshpate_umass_edu/compressed-llm/envs/context-compressio-py3.10/lib/python3.10/site-packages/transformers/models/gpt2/modeling_gpt2.py", line 888, in forward
    outputs = block(
  File "/work/pi_dhruveshpate_umass_edu/compressed-llm/envs/context-compressio-py3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/work/pi_dhruveshpate_umass_edu/compressed-llm/envs/context-compressio-py3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/work/pi_dhruveshpate_umass_edu/compressed-llm/envs/context-compressio-py3.10/lib/python3.10/site-packages/transformers/models/gpt2/modeling_gpt2.py", line 390, in forward
    attn_outputs = self.attn(
  File "/work/pi_dhruveshpate_umass_edu/compressed-llm/envs/context-compressio-py3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/work/pi_dhruveshpate_umass_edu/compressed-llm/envs/context-compressio-py3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/work/pi_dhruveshpate_umass_edu/compressed-llm/envs/context-compressio-py3.10/lib/python3.10/site-packages/transformers/models/gpt2/modeling_gpt2.py", line 331, in forward
    attn_output, attn_weights = self._attn(query, key, value, attention_mask, head_mask)
  File "/work/pi_dhruveshpate_umass_edu/compressed-llm/envs/context-compressio-py3.10/lib/python3.10/site-packages/transformers/models/gpt2/modeling_gpt2.py", line 202, in _attn
    attn_weights = torch.where(causal_mask, attn_weights.to(attn_weights.dtype), mask_value)
RuntimeError: The size of tensor a (1024) must match the size of tensor b (2515) at non-singleton dimension 3

This is the issue I am going into when I want to apply Selective context for pubmed dataset (ccdv/pubmed-summarization) with GPT-2 as the Language model. I wanted to confirm is it due to the some of the sentence in the article text being too long? Do you think using any other longer LM like LLama or Gemma might be better here? 

It would be great and be very helpfiul if you could provide your feedback here !

**Comment by Sriharsha-hatwar** [comment]
Also, I have another question, I am trying to parallelize the process, currently, I am doing it one by one where, I am giving dataset instance one at a time. Is there any way, we can instead give batches of instance and get the Selective context for a batch at a time? Please let me know. I would want to use this to speed up the process.

**Comment by liyucheng09** [comment]
1) for the first issue, there is a mismatch between gpt-2's max_length (1024) and your input (2515). So the solution is to use a model with larger max_length. Consider replace gpt-2 with gemma-2b for example, which has a context size of 8k, or mistral that got a context size of 32k.

2) I understand the need to do selective context in batches. I think that's not difficult to add batches support in selective context. You can simple rewrite the logic in `_lexical_unit` to do batched self-information computing and add a for-loop afterwards. It would take about 50 lines of code i guess.

Feel free to give this project a pr, if you find the batched operation is really helping!

**Comment by Sriharsha-hatwar** [comment]
Hey @liyucheng09 . Thanks a lot, I did replace the logic as you say with Gemma-2b (Even with Quantized model). However, it is extremely long and time consuming. I will try to parallelize and give a PR to your repo. Thanks a lot for getting back to me !
